server:
  port: 8580

spring:
  application:
    name: inventory-failover-service

inventory-failover:
  default:
    product-code: "0"
    quantity: 999

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/