server:
  port: 8185
spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///catalog
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "circuitbreakers", "circuitbreakerevents"]
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  circuitbreaker:
    enabled: true
